import { UserProfile, ProfileSticker } from '../types';

export const INITIAL_INTEREST_TAGS = [
  '☕ 카페투어',
  '🏃 러닝/마라톤',
  '🍷 와인/위스키',
  '✈️ 해외여행',
  '🎨 전시회/미술',
  '💪 헬스/웨이트',
  '🏕️ 캠핑/글램핑',
  '🎬 영화/넷플릭스',
  '🍣 맛집탐방',
  '🎸 음악감상/공연',
  '🐶 반려견 산책',
  '🎾 테니스/골프',
  '📚 독서/스터디',
  '🍳 요리/베이킹',
  '📸 사진촬영',
  '🧗 클라이밍'
];

export const AVAILABLE_STICKERS: ProfileSticker[] = [
  { id: 'stk_1', emoji: '✨', label: '훈훈비주얼', category: 'charm' },
  { id: 'stk_2', emoji: '🌟', label: '심쿵매력', category: 'charm' },
  { id: 'stk_3', emoji: '☕', label: '커피메이트', category: 'vibe' },
  { id: 'stk_4', emoji: '🗣️', label: '대화맛집', category: 'vibe' },
  { id: 'stk_5', emoji: '👔', label: '센스쟁이', category: 'personality' },
  { id: 'stk_6', emoji: '🌸', label: '인간비타민', category: 'personality' },
  { id: 'stk_7', emoji: '🐶', label: '댕댕이상', category: 'charm' },
  { id: 'stk_8', emoji: '🐱', label: '냥이상', category: 'charm' },
  { id: 'stk_9', emoji: '🎶', label: '취향저격', category: 'vibe' },
  { id: 'stk_10', emoji: '💯', label: '친절매너', category: 'manner' },
  { id: 'stk_11', emoji: '🍽️', label: '맛잘알', category: 'vibe' },
  { id: 'stk_12', emoji: '🏃', label: '운동메이트', category: 'personality' },
];

export const INITIAL_PROFILES: Omit<UserProfile, 'location' | 'distanceKm'>[] = [
  {
    id: 'user_1',
    email: 'jisoo.kim@korea.kr',
    name: '김지수',
    gender: 'female',
    birthDate: '1998-04-15',
    age: 26,
    company: '공무원 (중앙행정기관 주무관)',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80',
    bio: '주말엔 조용한 성수동 카페에서 드립 커피 마시며 전시회 보는 걸 좋아해요. 대화가 잘 통하고 따뜻한 분과 맛있는 브런치 먹으러 가고 싶어요!',
    interests: ['☕ 카페투어', '🎨 전시회/미술', '🍷 와인/위스키', '📸 사진촬영'],
    isOnline: true,
    verifiedEmail: true,
    createdAt: Date.now() - 86400000 * 10,
    lastActive: Date.now() - 25000,
    popularity: 118,
    isTestAccount: true,
    stickers: {
      '✨ 훈훈비주얼': 14,
      '☕ 커피메이트': 9,
      '🌸 인간비타민': 11,
      '🗣️ 대화맛집': 6,
    },
  },
  {
    id: 'user_2',
    email: 'minho.lee@kepco.co.kr',
    name: '이민호',
    gender: 'male',
    birthDate: '1995-11-20',
    age: 29,
    company: '한국전력공사 (전력망 엔지니어)',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&auto=format&fit=crop&q=80',
    bio: '퇴근 후 한강 러닝하고 주말엔 맛집 탐방하는 게 힐링이에요. 긍정적인 에너지를 주고받을 수 있는 인연을 찾고 있습니다. 편하게 인사해요 :)',
    interests: ['🏃 러닝/마라톤', '🍣 맛집탐방', '✈️ 해외여행', '🎾 테니스/골프'],
    isOnline: true,
    verifiedEmail: true,
    createdAt: Date.now() - 86400000 * 5,
    lastActive: Date.now() - 65000,
    popularity: 112,
    isTestAccount: true,
    stickers: {
      '🏃 운동메이트': 15,
      '👔 센스쟁이': 8,
      '💯 친절매너': 12,
      '🐶 댕댕이상': 7,
    },
  },
  {
    id: 'user_3',
    email: 'sujin.park@lh.or.kr',
    name: '박수진',
    gender: 'female',
    birthDate: '1997-08-12',
    age: 27,
    company: '한국토지주택공사 (도시재생기획)',
    photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=500&auto=format&fit=crop&q=80',
    bio: '새로운 곳 여행하고 다양한 이야기 나누는 걸 좋아합니다. 솔직하고 다정한 사람에게 끌려요. 같이 가볍게 산책하거나 와인 한잔 어떠세요?',
    interests: ['✈️ 해외여행', '🍷 와인/위스키', '🍣 맛집탐방', '🎸 음악감상/공연'],
    isOnline: true,
    verifiedEmail: true,
    createdAt: Date.now() - 86400000 * 3,
    lastActive: Date.now() - 15000,
    popularity: 125,
    isTestAccount: true,
    stickers: {
      '🌟 심쿵매력': 18,
      '🍽️ 맛잘알': 10,
      '🎶 취향저격': 13,
      '✨ 훈훈비주얼': 16,
    },
  },
  {
    id: 'user_4',
    email: 'hyunwoo.jung@korail.com',
    name: '정현우',
    gender: 'male',
    birthDate: '1994-03-05',
    age: 30,
    company: '한국철도공사 (운영관리 본부)',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&auto=format&fit=crop&q=80',
    bio: '일상의 작은 행복을 함께 나눌 인연을 찾습니다. 운동과 맛있는 요리를 즐겨요. 서로 존중하며 편안하게 지낼 수 있는 분 환영합니다!',
    interests: ['💪 헬스/웨이트', '🍳 요리/베이킹', '🏕️ 캠핑/글램핑', '🎬 영화/넷플릭스'],
    isOnline: false,
    verifiedEmail: true,
    createdAt: Date.now() - 86400000 * 7,
    lastActive: Date.now() - 12 * 60 * 1000,
    popularity: 106,
    isTestAccount: true,
    stickers: {
      '💯 친절매너': 14,
      '🍽️ 맛잘알': 8,
      '👔 센스쟁이': 7,
    },
  },
  {
    id: 'user_5',
    email: 'chaewon.yoon@seoul.go.kr',
    name: '윤채원',
    gender: 'female',
    birthDate: '1999-01-28',
    age: 25,
    company: '서울특별시청 (문화정책과)',
    photoUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=500&auto=format&fit=crop&q=80',
    bio: '주말엔 댕댕이랑 올림픽공원 산책하고 베이킹하는 집순이이자 여행러입니다. 코드가 맞는 분과 소소한 일상을 공유하고 싶어요 ✨',
    interests: ['🐶 반려견 산책', '🍳 요리/베이킹', '☕ 카페투어', '🎬 영화/넷플릭스'],
    isOnline: true,
    verifiedEmail: true,
    createdAt: Date.now() - 86400000 * 2,
    lastActive: Date.now() - 40000,
    popularity: 121,
    isTestAccount: true,
    stickers: {
      '🐶 댕댕이상': 19,
      '🌸 인간비타민': 15,
      '☕ 커피메이트': 11,
    },
  },
  {
    id: 'user_6',
    email: 'dohyun.kang@kwater.or.kr',
    name: '강도현',
    gender: 'male',
    birthDate: '1996-06-19',
    age: 28,
    company: '한국수자원공사 (연구원)',
    photoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=500&auto=format&fit=crop&q=80',
    bio: '클라이밍과 서핑 좋아하는 활동적인 성격이에요. 유머 감각 있고 긍정적인 바이브 가진 분과 주말에 액티비티나 드라이브 가고 싶습니다!',
    interests: ['🧗 클라이밍', '✈️ 해외여행', '🎾 테니스/골프', '🏕️ 캠핑/글램핑'],
    isOnline: false,
    verifiedEmail: true,
    createdAt: Date.now() - 86400000 * 4,
    lastActive: Date.now() - 28 * 60 * 1000,
    popularity: 108,
    isTestAccount: true,
    stickers: {
      '🏃 운동메이트': 12,
      '👔 센스쟁이': 9,
      '🗣️ 대화맛집': 7,
    },
  },
  {
    id: 'user_7',
    email: 'eunji.song@nhis.or.kr',
    name: '송은지',
    gender: 'female',
    birthDate: '1996-10-03',
    age: 28,
    company: '국민건강보험공단 (본부 대리)',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=500&auto=format&fit=crop&q=80',
    bio: '인디 음악 라이브 공연 보고 서점 탐방하는 거 좋아해요. 잔잔한 대화 속에서 서로의 취향을 알아가는 설렘을 느끼고 싶어요 🌿',
    interests: ['🎸 음악감상/공연', '📚 독서/스터디', '☕ 카페투어', '🎨 전시회/미술'],
    isOnline: false,
    verifiedEmail: true,
    createdAt: Date.now() - 86400000 * 8,
    lastActive: Date.now() - 35 * 60 * 1000,
    popularity: 115,
    isTestAccount: true,
    stickers: {
      '🎶 취향저격': 16,
      '☕ 커피메이트': 13,
      '🐱 냥이상': 8,
    },
  },
  {
    id: 'user_8',
    email: 'taehyung.choi@ex.co.kr',
    name: '최태형',
    gender: 'male',
    birthDate: '1993-12-14',
    age: 31,
    company: '한국도로공사 (스마트교통팀)',
    photoUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=500&auto=format&fit=crop&q=80',
    bio: '드라이브와 캠핑, 좋은 음악 듣는 시간들을 소중히 생각합니다. 서로에게 든든한 휴식처가 되어줄 좋은 사람을 만나고 싶어요.',
    interests: ['🏕️ 캠핑/글램핑', '🚗 드라이브', '🍷 와인/위스키', '💪 헬스/웨이트'],
    isOnline: true,
    verifiedEmail: true,
    createdAt: Date.now() - 86400000 * 12,
    lastActive: Date.now() - 80000,
    popularity: 104,
    isTestAccount: true,
    stickers: {
      '💯 친절매너': 11,
      '👔 센스쟁이': 6,
      '✨ 훈훈비주얼': 8,
    },
  },
  {
    id: 'user_9',
    email: 'yuna.han@knto.or.kr',
    name: '한유나',
    gender: 'female',
    birthDate: '1997-03-22',
    age: 27,
    company: '한국관광공사 (해외마케팅팀)',
    photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=500&auto=format&fit=crop&q=80',
    bio: '영화와 콘서트 보는 걸 사랑해요. 위트 있고 대화 코드가 통하는 분과 즐거운 주말을 보내고 싶습니다!',
    interests: ['🎬 영화/넷플릭스', '🎸 음악감상/공연', '🍣 맛집탐방', '☕ 카페투어'],
    isOnline: false,
    verifiedEmail: true,
    createdAt: Date.now() - 86400000 * 15,
    lastActive: Date.now() - 42 * 60 * 1000,
    popularity: 119,
    isTestAccount: true,
    stickers: {
      '🌸 인간비타민': 17,
      '🗣️ 대화맛집': 14,
    },
  },
  {
    id: 'user_10',
    email: 'junho.shin@nps.or.kr',
    name: '신준호',
    gender: 'male',
    birthDate: '1995-05-18',
    age: 29,
    company: '국민연금공단 (기금운용본부)',
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=500&auto=format&fit=crop&q=80',
    bio: '주말엔 자전거 라이딩과 감성 카페 다니는 걸 좋아해요. 성격은 차분하지만 유쾌한 반전 매력이 있습니다!',
    interests: ['☕ 카페투어', '🏃 러닝/마라톤', '🏕️ 캠핑/글램핑', '🍣 맛집탐방'],
    isOnline: true,
    verifiedEmail: true,
    createdAt: Date.now() - 86400000 * 6,
    lastActive: Date.now() - 45000,
    popularity: 110,
    isTestAccount: true,
    stickers: {
      '☕ 커피메이트': 12,
      '✨ 훈훈비주얼': 9,
    },
  },
  {
    id: 'user_11',
    email: 'soyeon.lee@gg.go.kr',
    name: '이소연',
    gender: 'female',
    birthDate: '1998-09-09',
    age: 26,
    company: '경기도청 (도시정책관)',
    photoUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=500&auto=format&fit=crop&q=80',
    bio: '자연 속에서 여유롭게 산책하고 맛있는 브런치 먹는 걸 좋아해요. 진솔하고 따뜻한 인연을 기다립니다 🌿',
    interests: ['🎨 전시회/미술', '🎬 영화/넷플릭스', '🍷 와인/위스키', '📸 사진촬영'],
    isOnline: true,
    verifiedEmail: true,
    createdAt: Date.now() - 86400000 * 4,
    lastActive: Date.now() - 15000,
    popularity: 122,
    isTestAccount: true,
    stickers: {
      '🌟 심쿵매력': 15,
      '🌸 인간비타민': 13,
    },
  }
];
